spring:
  application:
    name: Location Test
  config:
    use-legacy-processing: true
  profiles:
    active: local
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myApp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Blue123
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20

logging:
  level:
    root: info